# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zadanie7_part1_var1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zadanie7_part1_var1(object):
    def setupUi(self, Zadanie7_part1_var1):
        Zadanie7_part1_var1.setObjectName("Zadanie7_part1_var1")
        Zadanie7_part1_var1.resize(421, 503)
        self.label_title = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_title.setGeometry(QtCore.QRect(20, 20, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_title.setFont(font)
        self.label_title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_word_5 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_5.setGeometry(QtCore.QRect(80, 320, 81, 20))
        self.label_word_5.setObjectName("label_word_5")
        self.lineEdit_answer_3 = QtWidgets.QLineEdit(Zadanie7_part1_var1)
        self.lineEdit_answer_3.setGeometry(QtCore.QRect(10, 200, 31, 20))
        self.lineEdit_answer_3.setObjectName("lineEdit_answer_3")
        self.pushButton_answer = QtWidgets.QPushButton(Zadanie7_part1_var1)
        self.pushButton_answer.setGeometry(QtCore.QRect(130, 460, 101, 31))
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.label_number_1 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_1.setGeometry(QtCore.QRect(60, 90, 16, 20))
        self.label_number_1.setObjectName("label_number_1")
        self.label_number_4 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_4.setGeometry(QtCore.QRect(60, 260, 16, 20))
        self.label_number_4.setObjectName("label_number_4")
        self.label_word_3 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_3.setGeometry(QtCore.QRect(80, 200, 81, 20))
        self.label_word_3.setObjectName("label_word_3")
        self.label_word_4 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_4.setGeometry(QtCore.QRect(80, 260, 81, 20))
        self.label_word_4.setObjectName("label_word_4")
        self.label_word_1 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_1.setGeometry(QtCore.QRect(80, 90, 111, 31))
        self.label_word_1.setObjectName("label_word_1")
        self.label_word_2 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_2.setGeometry(QtCore.QRect(80, 130, 81, 20))
        self.label_word_2.setObjectName("label_word_2")
        self.lineEdit_answer_4 = QtWidgets.QLineEdit(Zadanie7_part1_var1)
        self.lineEdit_answer_4.setGeometry(QtCore.QRect(10, 260, 31, 20))
        self.lineEdit_answer_4.setObjectName("lineEdit_answer_4")
        self.lineEdit_answer_2 = QtWidgets.QLineEdit(Zadanie7_part1_var1)
        self.lineEdit_answer_2.setGeometry(QtCore.QRect(10, 130, 31, 20))
        self.lineEdit_answer_2.setObjectName("lineEdit_answer_2")
        self.lineEdit_answer_1 = QtWidgets.QLineEdit(Zadanie7_part1_var1)
        self.lineEdit_answer_1.setGeometry(QtCore.QRect(10, 90, 31, 20))
        self.lineEdit_answer_1.setText("")
        self.lineEdit_answer_1.setObjectName("lineEdit_answer_1")
        self.label_number_2 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_2.setGeometry(QtCore.QRect(60, 130, 16, 20))
        self.label_number_2.setObjectName("label_number_2")
        self.label_number_5 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_5.setGeometry(QtCore.QRect(60, 320, 16, 20))
        self.label_number_5.setObjectName("label_number_5")
        self.label_number_3 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_3.setGeometry(QtCore.QRect(60, 200, 16, 20))
        self.label_number_3.setObjectName("label_number_3")
        self.lineEdit_answer_5 = QtWidgets.QLineEdit(Zadanie7_part1_var1)
        self.lineEdit_answer_5.setGeometry(QtCore.QRect(10, 320, 31, 20))
        self.lineEdit_answer_5.setObjectName("lineEdit_answer_5")
        self.label_word_17 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_17.setGeometry(QtCore.QRect(210, 260, 201, 51))
        self.label_word_17.setObjectName("label_word_17")
        self.label_word_20 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_20.setGeometry(QtCore.QRect(210, 420, 201, 31))
        self.label_word_20.setObjectName("label_word_20")
        self.label_word_23 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_23.setGeometry(QtCore.QRect(210, 200, 201, 51))
        self.label_word_23.setObjectName("label_word_23")
        self.label_word_24 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_24.setGeometry(QtCore.QRect(210, 370, 201, 31))
        self.label_word_24.setObjectName("label_word_24")
        self.label_word_26 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_26.setGeometry(QtCore.QRect(210, 320, 201, 31))
        self.label_word_26.setObjectName("label_word_26")
        self.label_word_29 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_29.setGeometry(QtCore.QRect(210, 90, 201, 31))
        self.label_word_29.setObjectName("label_word_29")
        self.label_word_30 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_word_30.setGeometry(QtCore.QRect(210, 130, 201, 61))
        self.label_word_30.setObjectName("label_word_30")
        self.label_number_6 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_6.setGeometry(QtCore.QRect(200, 90, 16, 20))
        self.label_number_6.setObjectName("label_number_6")
        self.label_number_7 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_7.setGeometry(QtCore.QRect(200, 130, 16, 20))
        self.label_number_7.setObjectName("label_number_7")
        self.label_number_8 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_8.setGeometry(QtCore.QRect(200, 320, 16, 20))
        self.label_number_8.setObjectName("label_number_8")
        self.label_number_9 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_9.setGeometry(QtCore.QRect(200, 200, 16, 20))
        self.label_number_9.setObjectName("label_number_9")
        self.label_number_10 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_10.setGeometry(QtCore.QRect(200, 260, 16, 20))
        self.label_number_10.setObjectName("label_number_10")
        self.label_number_11 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_11.setGeometry(QtCore.QRect(200, 370, 16, 20))
        self.label_number_11.setObjectName("label_number_11")
        self.label_number_12 = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_number_12.setGeometry(QtCore.QRect(200, 420, 16, 20))
        self.label_number_12.setObjectName("label_number_12")
        self.label_timer = QtWidgets.QLabel(Zadanie7_part1_var1)
        self.label_timer.setGeometry(QtCore.QRect(240, 460, 171, 31))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")

        self.retranslateUi(Zadanie7_part1_var1)
        QtCore.QMetaObject.connectSlotsByName(Zadanie7_part1_var1)

    def retranslateUi(self, Zadanie7_part1_var1):
        _translate = QtCore.QCoreApplication.translate
        Zadanie7_part1_var1.setWindowTitle(_translate("Zadanie7_part1_var1", "Form"))
        self.label_title.setText(_translate("Zadanie7_part1_var1", "Задание 7.*\n"
" Сопоставьте термины (А)\n"
" с их определениями (Б)."))
        self.label_word_5.setText(_translate("Zadanie7_part1_var1", "Insulators block …"))
        self.pushButton_answer.setText(_translate("Zadanie7_part1_var1", "Далее"))
        self.label_number_1.setText(_translate("Zadanie7_part1_var1", "1"))
        self.label_number_4.setText(_translate("Zadanie7_part1_var1", "4"))
        self.label_word_3.setText(_translate("Zadanie7_part1_var1", "Resistance is…"))
        self.label_word_4.setText(_translate("Zadanie7_part1_var1", "Ohm is …"))
        self.label_word_1.setText(_translate("Zadanie7_part1_var1", "A passive component\n"
" of a circuit …"))
        self.label_word_2.setText(_translate("Zadanie7_part1_var1", "Resistor is …"))
        self.label_number_2.setText(_translate("Zadanie7_part1_var1", "2"))
        self.label_number_5.setText(_translate("Zadanie7_part1_var1", "5"))
        self.label_number_3.setText(_translate("Zadanie7_part1_var1", "3"))
        self.label_word_17.setText(_translate("Zadanie7_part1_var1", "… large amount of electric current and\n"
" allow very small amount of electric\n"
" current."))
        self.label_word_20.setText(_translate("Zadanie7_part1_var1", "… a device consisting of two electrodes\n"
" having unidirectional conduction."))
        self.label_word_23.setText(_translate("Zadanie7_part1_var1", "… is an electronic component containing\n"
" no source of power, in contrast to active\n"
" components."))
        self.label_word_24.setText(_translate("Zadanie7_part1_var1", "… the property of a conductor to\n"
" accumulate electric charge."))
        self.label_word_26.setText(_translate("Zadanie7_part1_var1", "… the device or component used to\n"
" restrict the electric current."))
        self.label_word_29.setText(_translate("Zadanie7_part1_var1", "… restricting the flow of electrons\n"
" or electric current to a certain level."))
        self.label_word_30.setText(_translate("Zadanie7_part1_var1", "… the amount of electric current blocked\n"
" by the resistor and allowed one ampere\n"
" of electric current when an applied\n"
" voltage of one volt is kept constant."))
        self.label_number_6.setText(_translate("Zadanie7_part1_var1", "1"))
        self.label_number_7.setText(_translate("Zadanie7_part1_var1", "2"))
        self.label_number_8.setText(_translate("Zadanie7_part1_var1", "5"))
        self.label_number_9.setText(_translate("Zadanie7_part1_var1", "3"))
        self.label_number_10.setText(_translate("Zadanie7_part1_var1", "4"))
        self.label_number_11.setText(_translate("Zadanie7_part1_var1", "6"))
        self.label_number_12.setText(_translate("Zadanie7_part1_var1", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Zadanie7_part1_var1 = QtWidgets.QWidget()
    ui = Ui_Zadanie7_part1_var1()
    ui.setupUi(Zadanie7_part1_var1)
    Zadanie7_part1_var1.show()
    sys.exit(app.exec_())
