# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zadanie4_part2_var1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zadanie4_part2_var1(object):
    def setupUi(self, Zadanie4_part2_var1):
        Zadanie4_part2_var1.setObjectName("Zadanie4_part2_var1")
        Zadanie4_part2_var1.resize(425, 619)
        self.label_title = QtWidgets.QLabel(Zadanie4_part2_var1)
        self.label_title.setGeometry(QtCore.QRect(0, 10, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_title.setFont(font)
        self.label_title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.pushButton_answer = QtWidgets.QPushButton(Zadanie4_part2_var1)
        self.pushButton_answer.setGeometry(QtCore.QRect(310, 570, 101, 31))
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.textBrowser = QtWidgets.QTextBrowser(Zadanie4_part2_var1)
        self.textBrowser.setGeometry(QtCore.QRect(20, 90, 331, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(Zadanie4_part2_var1)
        self.lineEdit.setGeometry(QtCore.QRect(360, 140, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Zadanie4_part2_var1)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 250, 331, 101))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Zadanie4_part2_var1)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 300, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Zadanie4_part2_var1)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 370, 331, 181))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Zadanie4_part2_var1)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 420, 51, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_show_text = QtWidgets.QPushButton(Zadanie4_part2_var1)
        self.pushButton_show_text.setGeometry(QtCore.QRect(20, 560, 91, 31))
        self.pushButton_show_text.setObjectName("pushButton_show_text")
        self.label_timer = QtWidgets.QLabel(Zadanie4_part2_var1)
        self.label_timer.setGeometry(QtCore.QRect(120, 570, 161, 31))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label_img = QtWidgets.QLabel(Zadanie4_part2_var1)
        self.label_img.setGeometry(QtCore.QRect(0, 0, 421, 631))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("../../../img/for_tests.jpg"))
        self.label_img.setObjectName("label_img")
        self.label_img.raise_()
        self.label_title.raise_()
        self.pushButton_answer.raise_()
        self.textBrowser.raise_()
        self.lineEdit.raise_()
        self.textBrowser_2.raise_()
        self.lineEdit_2.raise_()
        self.textBrowser_3.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_show_text.raise_()
        self.label_timer.raise_()

        self.retranslateUi(Zadanie4_part2_var1)
        QtCore.QMetaObject.connectSlotsByName(Zadanie4_part2_var1)

    def retranslateUi(self, Zadanie4_part2_var1):
        _translate = QtCore.QCoreApplication.translate
        Zadanie4_part2_var1.setWindowTitle(_translate("Zadanie4_part2_var1", "Form"))
        self.label_title.setText(_translate("Zadanie4_part2_var1", "Задание 4.\n"
" Укажите номера предложений, куда могут быть\n"
" включены данные ниже части текста."))
        self.pushButton_answer.setText(_translate("Zadanie4_part2_var1", "Далее"))
        self.textBrowser.setHtml(_translate("Zadanie4_part2_var1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Calibri\',\'serif\'; font-size:11pt; color:#000000;\">a) Printing the numbers on large electronic components is very easy, but it is very difficult to print the numbers or resistance values on tiny components. Hence, instead of directly printing the numbers, we print the color codes or color bands. However, by using the latest printing technology we can directly print the numbers on resistors.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Zadanie4_part2_var1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Calibri\',\'serif\'; font-size:11pt; color:#000000;\">b) A simple inductor is made by looping a wire into a coil. When an electric current passes through the coil, a magnetic field is formed around it. This magnetic field causes the inductor to resist changes in the amount of current passing through it.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Zadanie4_part2_var1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Calibri\',\'serif\'; font-size:11pt; color:#000000;\">c) A passive element is an electrical component that does not generate power, but instead dissipates, stores, and/or releases it. Passive elements include resistances, capacitors, and coils (also called inductors). These components are labeled in circuit diagrams as Rs, Cs and Ls, respectively. In most circuits, they are connected to active elements, typically semiconductor devices such as amplifiers and digital logic chips.</span></p></body></html>"))
        self.pushButton_show_text.setText(_translate("Zadanie4_part2_var1", "Показать текст"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Zadanie4_part2_var1 = QtWidgets.QWidget()
    ui = Ui_Zadanie4_part2_var1()
    ui.setupUi(Zadanie4_part2_var1)
    Zadanie4_part2_var1.show()
    sys.exit(app.exec_())
