# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_test2(object):
    def setupUi(self, Form_test2):
        Form_test2.setObjectName("Form_test2")
        Form_test2.resize(400, 614)
        self.pushButton_answer = QtWidgets.QPushButton(Form_test2)
        self.pushButton_answer.setGeometry(QtCore.QRect(280, 580, 121, 23))
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.radioButton_answer1 = QtWidgets.QRadioButton(Form_test2)
        self.radioButton_answer1.setGeometry(QtCore.QRect(20, 170, 331, 31))
        self.radioButton_answer1.setObjectName("radioButton_answer1")
        self.radioButton_answer2 = QtWidgets.QRadioButton(Form_test2)
        self.radioButton_answer2.setGeometry(QtCore.QRect(20, 270, 351, 31))
        self.radioButton_answer2.setObjectName("radioButton_answer2")
        self.radioButton_answer3 = QtWidgets.QRadioButton(Form_test2)
        self.radioButton_answer3.setGeometry(QtCore.QRect(20, 380, 351, 31))
        self.radioButton_answer3.setObjectName("radioButton_answer3")
        self.radioButton_answer4 = QtWidgets.QRadioButton(Form_test2)
        self.radioButton_answer4.setGeometry(QtCore.QRect(20, 470, 351, 31))
        self.radioButton_answer4.setObjectName("radioButton_answer4")
        self.plainTextEdit_question = QtWidgets.QPlainTextEdit(Form_test2)
        self.plainTextEdit_question.setGeometry(QtCore.QRect(20, 10, 361, 71))
        self.plainTextEdit_question.setObjectName("plainTextEdit_question")
        self.label_timer = QtWidgets.QLabel(Form_test2)
        self.label_timer.setGeometry(QtCore.QRect(20, 580, 221, 16))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label_img_question = QtWidgets.QLabel(Form_test2)
        self.label_img_question.setGeometry(QtCore.QRect(20, 90, 351, 71))
        self.label_img_question.setText("")
        self.label_img_question.setObjectName("label_img_question")
        self.label_img_var4 = QtWidgets.QLabel(Form_test2)
        self.label_img_var4.setGeometry(QtCore.QRect(20, 510, 371, 61))
        self.label_img_var4.setText("")
        self.label_img_var4.setObjectName("label_img_var4")
        self.label_img_var2 = QtWidgets.QLabel(Form_test2)
        self.label_img_var2.setGeometry(QtCore.QRect(20, 310, 371, 61))
        self.label_img_var2.setText("")
        self.label_img_var2.setObjectName("label_img_var2")
        self.label_img_var3 = QtWidgets.QLabel(Form_test2)
        self.label_img_var3.setGeometry(QtCore.QRect(20, 410, 371, 61))
        self.label_img_var3.setText("")
        self.label_img_var3.setObjectName("label_img_var3")
        self.label_img_var1 = QtWidgets.QLabel(Form_test2)
        self.label_img_var1.setGeometry(QtCore.QRect(20, 200, 371, 61))
        self.label_img_var1.setText("")
        self.label_img_var1.setObjectName("label_img_var1")

        self.retranslateUi(Form_test2)
        QtCore.QMetaObject.connectSlotsByName(Form_test2)

    def retranslateUi(self, Form_test2):
        _translate = QtCore.QCoreApplication.translate
        Form_test2.setWindowTitle(_translate("Form_test2", "Form"))
        self.pushButton_answer.setText(_translate("Form_test2", "Ответить"))
        self.radioButton_answer1.setText(_translate("Form_test2", "Первый вариант ответа"))
        self.radioButton_answer2.setText(_translate("Form_test2", "Второй вариант ответа"))
        self.radioButton_answer3.setText(_translate("Form_test2", "Третий вариант ответа"))
        self.radioButton_answer4.setText(_translate("Form_test2", "Четвертый вариант ответа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_test2 = QtWidgets.QWidget()
    ui = Ui_Form_test2()
    ui.setupUi(Form_test2)
    Form_test2.show()
    sys.exit(app.exec_())
