# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_client_main(object):
    def setupUi(self, Form_client_main):
        Form_client_main.setObjectName("Form_client_main")
        Form_client_main.resize(235, 86)
        self.pushButton_test1 = QtWidgets.QPushButton(Form_client_main)
        self.pushButton_test1.setGeometry(QtCore.QRect(40, 20, 161, 23))
        self.pushButton_test1.setObjectName("pushButton_test1")
        self.pushButton_test2 = QtWidgets.QPushButton(Form_client_main)
        self.pushButton_test2.setGeometry(QtCore.QRect(40, 50, 161, 23))
        self.pushButton_test2.setObjectName("pushButton_test2")

        self.retranslateUi(Form_client_main)
        QtCore.QMetaObject.connectSlotsByName(Form_client_main)

    def retranslateUi(self, Form_client_main):
        _translate = QtCore.QCoreApplication.translate
        Form_client_main.setWindowTitle(_translate("Form_client_main", "Client"))
        self.pushButton_test1.setText(_translate("Form_client_main", "Тест №1"))
        self.pushButton_test2.setText(_translate("Form_client_main", "Тест №2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_client_main = QtWidgets.QWidget()
    ui = Ui_Form_client_main()
    ui.setupUi(Form_client_main)
    Form_client_main.show()
    sys.exit(app.exec_())
