# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_client_test1(object):
    def setupUi(self, Form_client_test1):
        Form_client_test1.setObjectName("Form_client_test1")
        Form_client_test1.resize(407, 613)
        self.radioButton_answer1 = QtWidgets.QRadioButton(Form_client_test1)
        self.radioButton_answer1.setGeometry(QtCore.QRect(20, 170, 341, 31))
        self.radioButton_answer1.setObjectName("radioButton_answer1")
        self.pushButton = QtWidgets.QPushButton(Form_client_test1)
        self.pushButton.setGeometry(QtCore.QRect(270, 580, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_answer2 = QtWidgets.QRadioButton(Form_client_test1)
        self.radioButton_answer2.setGeometry(QtCore.QRect(20, 280, 351, 31))
        self.radioButton_answer2.setObjectName("radioButton_answer2")
        self.radioButton_answer3 = QtWidgets.QRadioButton(Form_client_test1)
        self.radioButton_answer3.setGeometry(QtCore.QRect(20, 380, 351, 31))
        self.radioButton_answer3.setObjectName("radioButton_answer3")
        self.radioButton_4 = QtWidgets.QRadioButton(Form_client_test1)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 480, 351, 31))
        self.radioButton_4.setObjectName("radioButton_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form_client_test1)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 10, 371, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_timer = QtWidgets.QLabel(Form_client_test1)
        self.label_timer.setGeometry(QtCore.QRect(20, 580, 221, 16))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label_img_question = QtWidgets.QLabel(Form_client_test1)
        self.label_img_question.setGeometry(QtCore.QRect(30, 90, 351, 71))
        self.label_img_question.setText("")
        self.label_img_question.setObjectName("label_img_question")
        self.label_img_var1 = QtWidgets.QLabel(Form_client_test1)
        self.label_img_var1.setGeometry(QtCore.QRect(20, 200, 371, 61))
        self.label_img_var1.setText("")
        self.label_img_var1.setObjectName("label_img_var1")
        self.label_img_var2 = QtWidgets.QLabel(Form_client_test1)
        self.label_img_var2.setGeometry(QtCore.QRect(20, 310, 371, 61))
        self.label_img_var2.setText("")
        self.label_img_var2.setObjectName("label_img_var2")
        self.label_img_var3 = QtWidgets.QLabel(Form_client_test1)
        self.label_img_var3.setGeometry(QtCore.QRect(20, 410, 371, 61))
        self.label_img_var3.setText("")
        self.label_img_var3.setObjectName("label_img_var3")
        self.label_img_var4 = QtWidgets.QLabel(Form_client_test1)
        self.label_img_var4.setGeometry(QtCore.QRect(20, 510, 371, 61))
        self.label_img_var4.setText("")
        self.label_img_var4.setObjectName("label_img_var4")

        self.retranslateUi(Form_client_test1)
        QtCore.QMetaObject.connectSlotsByName(Form_client_test1)

    def retranslateUi(self, Form_client_test1):
        _translate = QtCore.QCoreApplication.translate
        Form_client_test1.setWindowTitle(_translate("Form_client_test1", "Form"))
        self.radioButton_answer1.setText(_translate("Form_client_test1", "Первый вариант ответа"))
        self.pushButton.setText(_translate("Form_client_test1", "Ответить"))
        self.radioButton_answer2.setText(_translate("Form_client_test1", "Второй вариант ответа"))
        self.radioButton_answer3.setText(_translate("Form_client_test1", "Третий вариант ответа"))
        self.radioButton_4.setText(_translate("Form_client_test1", "Четвертый вариант ответа"))
        self.plainTextEdit.setPlainText(_translate("Form_client_test1", "пывпвп\n"
"ывпав"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_client_test1 = QtWidgets.QWidget()
    ui = Ui_Form_client_test1()
    ui.setupUi(Form_client_test1)
    Form_client_test1.show()
    sys.exit(app.exec_())
