# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_client_login(object):
    def setupUi(self, Form_client_login):
        Form_client_login.setObjectName("Form_client_login")
        Form_client_login.resize(375, 101)
        self.label_fio = QtWidgets.QLabel(Form_client_login)
        self.label_fio.setGeometry(QtCore.QRect(130, 10, 121, 20))
        self.label_fio.setObjectName("label_fio")
        self.pushButton_fio = QtWidgets.QPushButton(Form_client_login)
        self.pushButton_fio.setGeometry(QtCore.QRect(150, 70, 75, 23))
        self.pushButton_fio.setObjectName("pushButton_fio")
        self.comboBox_variant = QtWidgets.QComboBox(Form_client_login)
        self.comboBox_variant.setGeometry(QtCore.QRect(110, 40, 151, 22))
        self.comboBox_variant.setObjectName("comboBox_variant")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")
        self.comboBox_variant.addItem("")

        self.retranslateUi(Form_client_login)
        QtCore.QMetaObject.connectSlotsByName(Form_client_login)

    def retranslateUi(self, Form_client_login):
        _translate = QtCore.QCoreApplication.translate
        Form_client_login.setWindowTitle(_translate("Form_client_login", "login"))
        self.label_fio.setText(_translate("Form_client_login", "Вариант тестируемого"))
        self.pushButton_fio.setText(_translate("Form_client_login", "Войти"))
        self.comboBox_variant.setItemText(0, _translate("Form_client_login", "1"))
        self.comboBox_variant.setItemText(1, _translate("Form_client_login", "2"))
        self.comboBox_variant.setItemText(2, _translate("Form_client_login", "3"))
        self.comboBox_variant.setItemText(3, _translate("Form_client_login", "4"))
        self.comboBox_variant.setItemText(4, _translate("Form_client_login", "5"))
        self.comboBox_variant.setItemText(5, _translate("Form_client_login", "6"))
        self.comboBox_variant.setItemText(6, _translate("Form_client_login", "7"))
        self.comboBox_variant.setItemText(7, _translate("Form_client_login", "8"))
        self.comboBox_variant.setItemText(8, _translate("Form_client_login", "9"))
        self.comboBox_variant.setItemText(9, _translate("Form_client_login", "10"))
        self.comboBox_variant.setItemText(10, _translate("Form_client_login", "11"))
        self.comboBox_variant.setItemText(11, _translate("Form_client_login", "12"))
        self.comboBox_variant.setItemText(12, _translate("Form_client_login", "13"))
        self.comboBox_variant.setItemText(13, _translate("Form_client_login", "14"))
        self.comboBox_variant.setItemText(14, _translate("Form_client_login", "15"))
        self.comboBox_variant.setItemText(15, _translate("Form_client_login", "16"))
        self.comboBox_variant.setItemText(16, _translate("Form_client_login", "17"))
        self.comboBox_variant.setItemText(17, _translate("Form_client_login", "18"))
        self.comboBox_variant.setItemText(18, _translate("Form_client_login", "19"))
        self.comboBox_variant.setItemText(19, _translate("Form_client_login", "20"))
        self.comboBox_variant.setItemText(20, _translate("Form_client_login", "21"))
        self.comboBox_variant.setItemText(21, _translate("Form_client_login", "22"))
        self.comboBox_variant.setItemText(22, _translate("Form_client_login", "23"))
        self.comboBox_variant.setItemText(23, _translate("Form_client_login", "24"))
        self.comboBox_variant.setItemText(24, _translate("Form_client_login", "25"))
        self.comboBox_variant.setItemText(25, _translate("Form_client_login", "26"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_client_login = QtWidgets.QWidget()
    ui = Ui_Form_client_login()
    ui.setupUi(Form_client_login)
    Form_client_login.show()
    sys.exit(app.exec_())
