# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text1_form_var1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Text1Form(object):
    def setupUi(self, Text1Form):
        Text1Form.setObjectName("Text1Form")
        Text1Form.resize(583, 700)
        self.axWidget = QAxContainer.QAxWidget(Text1Form)
        self.axWidget.setProperty("geometry", QtCore.QRect(20, 20, 551, 661))
        self.axWidget.setObjectName("axWidget")

        self.retranslateUi(Text1Form)
        QtCore.QMetaObject.connectSlotsByName(Text1Form)

    def retranslateUi(self, Text1Form):
        _translate = QtCore.QCoreApplication.translate
        Text1Form.setWindowTitle(_translate("Text1Form", "Form"))
from PyQt5 import QAxContainer


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Text1Form = QtWidgets.QWidget()
    ui = Ui_Text1Form()
    ui.setupUi(Text1Form)
    Text1Form.show()
    sys.exit(app.exec_())
