# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_questions.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_questions(object):
    def setupUi(self, Form_questions):
        Form_questions.setObjectName("Form_questions")
        Form_questions.resize(869, 435)
        self.tableWidget_question_list = QtWidgets.QTableWidget(Form_questions)
        self.tableWidget_question_list.setGeometry(QtCore.QRect(10, 10, 791, 271))
        self.tableWidget_question_list.setObjectName("tableWidget_question_list")
        self.tableWidget_question_list.setColumnCount(0)
        self.tableWidget_question_list.setRowCount(0)
        self.textEdit_add_new_question = QtWidgets.QTextEdit(Form_questions)
        self.textEdit_add_new_question.setGeometry(QtCore.QRect(10, 290, 791, 71))
        self.textEdit_add_new_question.setObjectName("textEdit_add_new_question")
        self.pushButton_add = QtWidgets.QPushButton(Form_questions)
        self.pushButton_add.setGeometry(QtCore.QRect(90, 370, 121, 23))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_dell = QtWidgets.QPushButton(Form_questions)
        self.pushButton_dell.setGeometry(QtCore.QRect(350, 370, 121, 23))
        self.pushButton_dell.setObjectName("pushButton_dell")
        self.pushButton_view_var = QtWidgets.QPushButton(Form_questions)
        self.pushButton_view_var.setGeometry(QtCore.QRect(220, 370, 121, 23))
        self.pushButton_view_var.setObjectName("pushButton_view_var")
        self.pushButton_new_val = QtWidgets.QPushButton(Form_questions)
        self.pushButton_new_val.setGeometry(QtCore.QRect(90, 400, 121, 23))
        self.pushButton_new_val.setObjectName("pushButton_new_val")
        self.pushButton_download_img = QtWidgets.QPushButton(Form_questions)
        self.pushButton_download_img.setGeometry(QtCore.QRect(640, 330, 111, 23))
        self.pushButton_download_img.setObjectName("pushButton_download_img")
        self.label_img_address = QtWidgets.QLabel(Form_questions)
        self.label_img_address.setGeometry(QtCore.QRect(580, 300, 401, 21))
        self.label_img_address.setObjectName("label_img_address")
        self.label_show_img = QtWidgets.QLabel(Form_questions)
        self.label_show_img.setGeometry(QtCore.QRect(580, 10, 404, 286))
        self.label_show_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show_img.setText("")
        self.label_show_img.setObjectName("label_show_img")
        self.pushButton_delete_img = QtWidgets.QPushButton(Form_questions)
        self.pushButton_delete_img.setGeometry(QtCore.QRect(770, 330, 111, 23))
        self.pushButton_delete_img.setObjectName("pushButton_delete_img")
        self.lineEdit_update_time = QtWidgets.QLineEdit(Form_questions)
        self.lineEdit_update_time.setGeometry(QtCore.QRect(590, 380, 91, 20))
        self.lineEdit_update_time.setObjectName("lineEdit_update_time")
        self.pushButton_update_time = QtWidgets.QPushButton(Form_questions)
        self.pushButton_update_time.setGeometry(QtCore.QRect(700, 380, 101, 23))
        self.pushButton_update_time.setObjectName("pushButton_update_time")

        self.retranslateUi(Form_questions)
        QtCore.QMetaObject.connectSlotsByName(Form_questions)

    def retranslateUi(self, Form_questions):
        _translate = QtCore.QCoreApplication.translate
        Form_questions.setWindowTitle(_translate("Form_questions", "Form"))
        self.pushButton_add.setText(_translate("Form_questions", "Добавить/Обновить"))
        self.pushButton_dell.setText(_translate("Form_questions", "Удалить"))
        self.pushButton_view_var.setText(_translate("Form_questions", "Просмотр ответов"))
        self.pushButton_new_val.setText(_translate("Form_questions", "Новая запись"))
        self.pushButton_download_img.setText(_translate("Form_questions", "Загрузка картинки"))
        self.label_img_address.setText(_translate("Form_questions", "Адрес картинки"))
        self.pushButton_delete_img.setText(_translate("Form_questions", "Удаление картинки"))
        self.lineEdit_update_time.setText(_translate("Form_questions", "100"))
        self.pushButton_update_time.setText(_translate("Form_questions", "Обновить время"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_questions = QtWidgets.QWidget()
    ui = Ui_Form_questions()
    ui.setupUi(Form_questions)
    Form_questions.show()
    sys.exit(app.exec_())
