# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_server(object):
    def setupUi(self, Form_server):
        Form_server.setObjectName("Form_server")
        Form_server.resize(463, 348)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form_server)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 461, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_work_db = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_work_db.setObjectName("pushButton_work_db")
        self.verticalLayout.addWidget(self.pushButton_work_db)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_delete_all = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_delete_all.setObjectName("pushButton_delete_all")
        self.verticalLayout_2.addWidget(self.pushButton_delete_all)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_server = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget_server.setObjectName("tableWidget_server")
        self.tableWidget_server.setColumnCount(0)
        self.tableWidget_server.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget_server)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form_server)
        QtCore.QMetaObject.connectSlotsByName(Form_server)

    def retranslateUi(self, Form_server):
        _translate = QtCore.QCoreApplication.translate
        Form_server.setWindowTitle(_translate("Form_server", "Server"))
        self.pushButton_work_db.setText(_translate("Form_server", "Работа с вопросами"))
        self.pushButton_delete_all.setText(_translate("Form_server", "Удалить результаты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_server = QtWidgets.QWidget()
    ui = Ui_Form_server()
    ui.setupUi(Form_server)
    Form_server.show()
    sys.exit(app.exec_())
